DROP TABLE CUSTOMER CASCADE CONSTRAINTS;

CREATE TABLE CUSTOMER (
CUS_ID NUMBER(25),
EMAIL VARCHAR2(50) NOT NULL,
PASSWORD VARCHAR2(30) NOT NULL,
PHONENUM NUMBER(10),
CONSTRAINT CUSPK PRIMARY KEY(CUS_ID)    
);

DROP TABLE PAYMENT CASCADE CONSTRAINTS; 

CREATE TABLE PAYMENT(
PAYMENT_ID NUMBER(25),
CARD_NUMBER NUMBER(16) NOT NULL,
EXPIRY_MONTH VARCHAR2(10),
EXPIRY_YEAR NUMBER(4),
CCV NUMBER(4),
NAME_ON_CARD VARCHAR2(20),
CUS_ID NUMBER,    
CONSTRAINT PAYPK PRIMARY KEY(PAYMENT_ID),
CONSTRAINT FORPAY FOREIGN KEY(CUS_ID) REFERENCES CUSTOMER(CUS_ID) ON DELETE SET NULL    
);


DROP TABLE BILLINGADDRESS CASCADE CONSTRAINTS;

CREATE TABLE BILLINGADDRESS (
CUS_ID NUMBER(25),
STREET_ADDRESS VARCHAR2(40),
APT_NUM VARCHAR2(10),   
CITY VARCHAR2(15),
STATE VARCHAR2(2),
ZIPCODE NUMBER(6),
CONSTRAINT PKBILL PRIMARY KEY(CUS_ID,STREET_ADDRESS,APT_NUM,CITY),    
CONSTRAINT FORBILL FOREIGN KEY(CUS_ID) REFERENCES CUSTOMER(CUS_ID) ON DELETE SET NULL    
);


DROP TABLE SHIPPINGADDRESS CASCADE CONSTRAINTS;

CREATE TABLE SHIPPINGADDRESS (
CUS_ID NUMBER(25),
STREET_ADDRESS VARCHAR2(40),
APT_NUM VARCHAR2(10),   
CITY VARCHAR2(15),
STATE VARCHAR2(2),
ZIPCODE NUMBER(6),
PHONENUMBER NUMBER(10),    
CONSTRAINT PKSHIP PRIMARY KEY(CUS_ID,STREET_ADDRESS,APT_NUM,CITY),    
CONSTRAINT FORSHIP FOREIGN KEY(CUS_ID) REFERENCES CUSTOMER(CUS_ID) ON DELETE SET NULL    
);


DROP TABLE DEPARTMENT CASCADE CONSTRAINTS;

CREATE TABLE DEPARTMENT (
DEPT_ID NUMBER(3) NOT NULL,
DAPT_NAME VARCHAR2(25) NOT NULL,   
CONSTRAINT PKDEPT PRIMARY KEY(DEPT_ID)    
);


DROP TABLE DEPTSUBCAT CASCADE CONSTRAINTS;

CREATE TABLE DEPTSUBCAT (
SUBCATEGORY_ID NUMBER(5) NOT NULL,
SUBCATEGORY_NAME VARCHAR2(20),    
DEPT_ID NUMBER(3),    
CONSTRAINT PKSUBCAT PRIMARY KEY(SUBCATEGORY_ID),
CONSTRAINT FORSUBCAT FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID) ON DELETE SET NULL     
);

DROP TABLE PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT (
PRODUCT_ID NUMBER(25) NOT NULL,
PRODUCT_NAME VARCHAR2(20) NOT NULL,
PRODUCT_DESCRIPTION VARCHAR2(150),
RATING NUMBER(1),
SELL_PRICE NUMBER(10) NOT NULL,
SUBCATEGORY_ID NUMBER(5),
CONSTRAINT PKPRO PRIMARY KEY(PRODUCT_ID),
CONSTRAINT FORPRO FOREIGN KEY(SUBCATEGORY_ID) REFERENCES DEPTSUBCAT(SUBCATEGORY_ID) ON DELETE SET NULL     
);

DROP TABLE PRODUCT_IMAGE CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT_IMAGE (
PRODUCT_ID NUMBER(25) NOT NULL,
IMAGE_URL VARCHAR2(100) NOT NULL,
CONSTRAINT FORIMG FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE SET NULL      
);


DROP TABLE PRODUCT_COMMENTS CASCADE CONSTRAINTS;

CREATE TABLE PRODUCT_COMMENTS (
COMMENT_ID NUMBER(25),     
PRODUCT_ID NUMBER(25) NOT NULL,
COMMENTS VARCHAR2(100) NOT NULL,
CUS_ID NUMBER(25),    
CONSTRAINT PKCOM PRIMARY KEY(COMMENT_ID),
CONSTRAINT FORCOM FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE SET NULL,
CONSTRAINT FORCOM1 FOREIGN KEY(CUS_ID) REFERENCES CUSTOMER(CUS_ID) ON DELETE SET NULL   
);



DROP TABLE SELLER CASCADE CONSTRAINTS;

CREATE TABLE SELLER (
SELLER_ID NUMBER(25) NOT NULL,
SELLER_NAME VARCHAR2(25),
PHONE_NUM NUMBER(10) NOT NULL,
ALTERNATE_PHONE NUMBER(10),
ADDRESS VARCHAR2(50),
CONSTRAINT PKSELL PRIMARY KEY(SELLER_ID) 
);



DROP TABLE WAREHOUSE CASCADE CONSTRAINTS;


CREATE TABLE WAREHOUSE (
W_ID NUMBER(25) NOT NULL,
ADDRESS VARCHAR2(50),
CAPACITY_IN_SQFT NUMBER(5),
RENT NUMBER(5),
CONSTRAINT PKWAR PRIMARY KEY(W_ID)     
);


DROP TABLE SELLS CASCADE CONSTRAINTS;
    
    
    CREATE TABLE SELLS (
    SALE_ID NUMBER(25) NOT NULL,
    SELLER_ID NUMBER(25),
    BUYING_DATE DATE,    
    PRODUCT_ID NUMBER(25),
    QUANTITY NUMBER(5),
    BUY_PRICE NUMBER(5),
    W_ID NUMBER(3),
    CONSTRAINT PKSE PRIMARY KEY(SALE_ID),
    CONSTRAINT FORSE FOREIGN KEY(SELLER_ID) REFERENCES SELLER(SELLER_ID) ON DELETE SET NULL,
    CONSTRAINT FORSE1 FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE SET NULL,
    CONSTRAINT FORSE2 FOREIGN KEY(W_ID) REFERENCES WAREHOUSE(W_ID) ON DELETE SET NULL 
    );

DROP TABLE ORDERS CASCADE CONSTRAINTS;

CREATE TABLE ORDERS (
ORDER_ID NUMBER(25) NOT NULL,
CUS_ID NUMBER(25),
ORDER_DATE DATE,
PRODUCT_ID NUMBER(25),
QTY NUMBER(2),
PAYMENT_ID NUMBER(25),
CONSTRAINT PKOR PRIMARY KEY(ORDER_ID),
CONSTRAINT FOROR FOREIGN KEY(CUS_ID) REFERENCES CUSTOMER(CUS_ID) ON DELETE SET NULL,
CONSTRAINT FOROR1 FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE SET NULL,
CONSTRAINT FOROR2 FOREIGN KEY(PAYMENT_ID) REFERENCES PAYMENT(PAYMENT_ID) ON DELETE SET NULL
);

DROP TABLE STOCK CASCADE CONSTRAINTS;

CREATE TABLE STOCK (
W_ID NUMBER(25),
PRODUCT_ID NUMBER(25),
QUANTITY NUMBER(5),
CONSTRAINT FORST1 FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE SET NULL,
CONSTRAINT FORST2 FOREIGN KEY(W_ID) REFERENCES WAREHOUSE(W_ID) ON DELETE SET NULL    
);

DROP TABLE EMPDEPT CASCADE CONSTRAINTS;

CREATE TABLE EMPDEPT (
DEPT_ID NUMBER(25) NOT NULL,
DEPT_NAME VARCHAR2(25),
NUMBER_OF_EMP NUMBER(5),
CONSTRAINT PKEMPDEP PRIMARY KEY(DEPT_ID)      
);

DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;


CREATE TABLE EMPLOYEE (
EMP_ID NUMBER(25) NOT NULL,
NAME VARCHAR2(15),
AGE NUMBER(3),
SSN NUMBER(10) NOT NULL,
SALARY NUMBER(6),
DEPT_ID NUMBER(25),
CONSTRAINT PKEMP PRIMARY KEY(EMP_ID),
CONSTRAINT FOREMP FOREIGN KEY(DEPT_ID) REFERENCES EMPDEPT(DEPT_ID) ON DELETE SET NULL   
);

DROP TABLE WAREHOUSE_EMP CASCADE CONSTRAINTS;

CREATE TABLE WAREHOUSE_EMP (
W_ID NUMBER(25),
EMP_ID NUMBER(25),
CONSTRAINT FORWREMP FOREIGN KEY(W_ID) REFERENCES WAREHOUSE(W_ID) ON DELETE SET NULL,
CONSTRAINT FORWREMP1 FOREIGN KEY(EMP_ID) REFERENCES EMPLOYEE(EMP_ID) ON DELETE SET NULL        
);
