------INSERTING INTO CUSTOMER TABLE------

DROP SEQUENCE CUS_SEQ;

create SEQUENCE CUS_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 ;

DECLARE

BEGIN 

FOR I IN 1..10000 LOOP
    INSERT INTO CUSTOMER              
     VALUES ( CUS_SEQ.NEXTVAL,             
              'jayapragash_b'||I||'@yahoo.com',                
              'qwerty1234',            
              6824149300+I    
              );  
    END LOOP;
    
END;  

------INSERTING INTO PAYMENT TABLE------

DROP SEQUENCE PAY_SEQ;

create SEQUENCE PAY_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 ;

SET SERVEROUTPUT ON;
DECLARE 
EXPIRY_MON PAYMENT.EXPIRY_MONTH%TYPE;
EXPIRY_YE PAYMENT.EXPIRY_YEAR%TYPE;
CC PAYMENT.CCV%TYPE;
NAME_ON_CAR PAYMENT.NAME_ON_CARD%TYPE;
CUS_I PAYMENT.CUS_ID%TYPE;


BEGIN 
  FOR I IN 1..10000 LOOP
  
  EXPIRY_MON := ROUND(DBMS_RANDOM.VALUE(1,12));
   EXPIRY_YE := ROUND(DBMS_RANDOM.VALUE(2018,2025));
   CC := ROUND(DBMS_RANDOM.VALUE(100,999));
    NAME_ON_CAR := DBMS_RANDOM.STRING('U',15);
    CUS_I := ROUND(DBMS_RANDOM.VALUE(1,10000));
    
    INSERT INTO PAYMENT              
     VALUES ( PAY_SEQ.NEXTVAL,             
            1000000000000000+I, 
            EXPIRY_MON,
            EXPIRY_YE,
            CC,
            NAME_ON_CAR,
            I      
              );  
    END LOOP;


END; 

------INSERTING INTO BILLING ADDRESS TABLE------


DECLARE 
APT BILLINGADDRESS.APT_NUM%TYPE;
ZIP BILLINGADDRESS.ZIPCODE%TYPE;
CITY BILLINGADDRESS.CITY%TYPE;
STREET BILLINGADDRESS.STREET_ADDRESS%TYPE;
ST BILLINGADDRESS.STATE%TYPE;


BEGIN 
  FOR I IN 1..10000 LOOP
  
  CASE ROUND(DBMS_RANDOM.VALUE(1,10))
  WHEN 1 THEN  ST := 'TX';
  WHEN 2 THEN  ST := 'TN';
  WHEN 3 THEN ST := 'AK';
  WHEN 4 THEN ST := 'AR';
  WHEN 5 THEN  ST := 'CA';
  WHEN 6 THEN  ST := 'NW';
  WHEN 7 THEN ST := 'BS';
  WHEN 8 THEN ST := 'FL';
  WHEN 9 THEN ST := 'NV';
  WHEN 10 THEN ST := 'NM';
  ELSE ST := 'CO';
  END CASE;
  
  
    APT := ROUND(DBMS_RANDOM.VALUE(100,999));
    ZIP := ROUND(DBMS_RANDOM.VALUE(111111,999999));
    STREET := DBMS_RANDOM.STRING('U',20);
    CITY := DBMS_RANDOM.STRING('U',10);
    
    INSERT INTO BILLINGADDRESS              
     VALUES ( I,             
            STREET, 
            APT,
            CITY,
            ST,
            ZIP     
              );  
    END LOOP;


END; 



------INSERTING INTO SHIPPING ADDRESS TABLE------

DECLARE 
APT SHIPPINGADDRESS.APT_NUM%TYPE;
ZIP SHIPPINGADDRESS.ZIPCODE%TYPE;
CITY SHIPPINGADDRESS.CITY%TYPE;
STREET SHIPPINGADDRESS.STREET_ADDRESS%TYPE;
ST SHIPPINGADDRESS.STATE%TYPE;


BEGIN 
  FOR I IN 1..10000 LOOP
  
  CASE ROUND(DBMS_RANDOM.VALUE(1,10))
  WHEN 1 THEN  ST := 'TX';
  WHEN 2 THEN  ST := 'TN';
  WHEN 3 THEN ST := 'AK';
  WHEN 4 THEN ST := 'AR';
  WHEN 5 THEN  ST := 'CA';
  WHEN 6 THEN  ST := 'NW';
  WHEN 7 THEN ST := 'BS';
  WHEN 8 THEN ST := 'FL';
  WHEN 9 THEN ST := 'NV';
  WHEN 10 THEN ST := 'NM';
  ELSE ST := 'CO';
  END CASE;
  
  
    APT := ROUND(DBMS_RANDOM.VALUE(100,999));
    ZIP := ROUND(DBMS_RANDOM.VALUE(111111,999999));
    STREET := DBMS_RANDOM.STRING('U',20);
    CITY := DBMS_RANDOM.STRING('U',10);
    
    INSERT INTO SHIPPINGADDRESS              
     VALUES ( I,             
            STREET, 
            APT,
            CITY,
            ST,
            ZIP,
            3800000000+I
              );  
    END LOOP;
END;  



-------INSERTING INTO DEPARTMENT TABLE--------

INSERT INTO DEPARTMENT VALUES (1,'MEN');
INSERT INTO DEPARTMENT VALUES (2,'WOMEN');
INSERT INTO DEPARTMENT VALUES (3,'BOYS');
INSERT INTO DEPARTMENT VALUES (4,'GIRLS');





-------INSERTING INTO DEPTSUBCAT TABLE--------

INSERT INTO DEPTSUBCAT VALUES (1,'SHIRTS',1);
INSERT INTO DEPTSUBCAT VALUES (2,'TRACKS',1);
INSERT INTO DEPTSUBCAT VALUES (3,'SHORTS',1);
INSERT INTO DEPTSUBCAT VALUES (4,'SHOES',1);
INSERT INTO DEPTSUBCAT VALUES (5,'JACKETS',1);

INSERT INTO DEPTSUBCAT VALUES (6,'SHIRTS',2);
INSERT INTO DEPTSUBCAT VALUES (7,'TRACKS',2);
INSERT INTO DEPTSUBCAT VALUES (8,'SHORTS',2);
INSERT INTO DEPTSUBCAT VALUES (9,'SHOES',2);
INSERT INTO DEPTSUBCAT VALUES (10,'JACKETS',2);

INSERT INTO DEPTSUBCAT VALUES (11,'SHIRTS',3);
INSERT INTO DEPTSUBCAT VALUES (12,'TRACKS',3);
INSERT INTO DEPTSUBCAT VALUES (13,'SHORTS',3);
INSERT INTO DEPTSUBCAT VALUES (14,'SHOES',3);
INSERT INTO DEPTSUBCAT VALUES (15,'JACKETS',3);

INSERT INTO DEPTSUBCAT VALUES (16,'SHIRTS',4);
INSERT INTO DEPTSUBCAT VALUES (17,'TRACKS',4);
INSERT INTO DEPTSUBCAT VALUES (18,'SHORTS',4);
INSERT INTO DEPTSUBCAT VALUES (19,'SHOES',4);
INSERT INTO DEPTSUBCAT VALUES (20,'JACKETS',4);


-------INSERTING INTO PRODUCT TABLE--------

DECLARE 
SELLP PRODUCT.SELL_PRICE%TYPE;
SUBCAT PRODUCT.SUBCATEGORY_ID%TYPE;
DES PRODUCT.PRODUCT_DESCRIPTION%TYPE;
RATING PRODUCT.RATING%TYPE;


BEGIN 
  FOR I IN 1..10000 LOOP
  
    RATING := ROUND(DBMS_RANDOM.VALUE(1,5));
    DES := DBMS_RANDOM.STRING('U',100);
    SELLP := ROUND(DBMS_RANDOM.VALUE(1000,1500));
    SUBCAT := ROUND(DBMS_RANDOM.VALUE(1,20));
    
    INSERT INTO PRODUCT              
     VALUES ( I,             
            'PRODUCT '||I, 
            DES,
            RATING,
            SELLP,
            SUBCAT
              );  
    END LOOP;
END;   




-------INSERTING INTO PRODUCT_IMAGE TABLE--------

DECLARE 

BEGIN 
  FOR I IN 1..10000 LOOP
  
    INSERT INTO PRODUCT_IMAGE              
     VALUES ( I,             
            'PRODUCTIMG1.JPG'
              );  
    END LOOP;
END;  




-------INSERTING INTO PRODUCT_COMMENTS TABLE--------

DROP SEQUENCE COM_SEQ;

create SEQUENCE COM_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 ;
DECLARE 
PRODUCTID PRODUCT_COMMENTS.PRODUCT_ID%TYPE;
COMMENTS PRODUCT_COMMENTS.COMMENTS%TYPE;
CID PRODUCT_COMMENTS.CUS_ID%TYPE;


BEGIN 
  FOR I IN 1..10000 LOOP
    PRODUCTID := ROUND(DBMS_RANDOM.VALUE(1,10000));
    COMMENTS := DBMS_RANDOM.STRING('U',100);
    CID := ROUND(DBMS_RANDOM.VALUE(1,10000));
    INSERT INTO PRODUCT_COMMENTS              
     VALUES ( COM_SEQ.NEXTVAL, 
             PRODUCTID,
                COMMENTS,
                CID
              );  
    END LOOP;
END;   




-------INSERTING INTO SELLER TABLE--------

DROP SEQUENCE SELL_SEQ;

create SEQUENCE SELL_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 ;
DECLARE 
ADDRESS SELLER.ADDRESS%TYPE;

BEGIN 
  FOR I IN 1..1000 LOOP

    ADDRESS := DBMS_RANDOM.STRING('U',45);

    INSERT INTO SELLER              
     VALUES ( SELL_SEQ.NEXTVAL, 
             'SELLER'||I,
                5000000000+I,
                6000000000+I,
                ADDRESS
              );  
    END LOOP;
END;   




-------INSERTING INTO WAREHOUSE TABLE--------

DROP SEQUENCE Q_SEQ;

create SEQUENCE W_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 ;
DECLARE 
ADDRESS WAREHOUSE.ADDRESS%TYPE;
CAP WAREHOUSE.CAPACITY_IN_SQFT%TYPE;
R WAREHOUSE.RENT%TYPE;

BEGIN 
  FOR I IN 1..30 LOOP
  
  
      CASE ROUND(DBMS_RANDOM.VALUE(1,5))
  WHEN 1 THEN  CAP := 10000; R := 5000;
  WHEN 2 THEN  CAP := 20000; R := 15000;
  WHEN 3 THEN CAP := 30000; R := 25000;
  WHEN 4 THEN CAP := 40000; R := 35000;
  WHEN 5 THEN  CAP := 50000; R := 45000;
  ELSE CAP := 0; R := 0;
  END CASE;

    ADDRESS := DBMS_RANDOM.STRING('U',45);

    INSERT INTO WAREHOUSE              
     VALUES ( W_SEQ.NEXTVAL, 
              ADDRESS,
              CAP,
              R
              );  
    END LOOP;
END;  



-------INSERTING INTO SELLS TABLE--------

DROP SEQUENCE SALE_SEQ;

create SEQUENCE SALE_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 ;

DECLARE 

DAT DATE;
DA SELLS.BUYING_DATE%TYPE;
SELLERID SELLS.SELLER_ID%TYPE;
PROID SELLS.PRODUCT_ID%TYPE;
QUAN SELLS.QUANTITY%TYPE;
BUY SELLS.BUY_PRICE%TYPE;
W SELLS.W_ID%TYPE;


BEGIN 

    DAT := '01-JAN-2016';

  FOR I IN 1..2 LOOP
        DA := TO_DATE('DAT + ROUND(DBMS_RANDOM.value(0,366))','MM');
        SELLERID := ROUND(DBMS_RANDOM.VALUE(1,1000));
        PROID := ROUND(DBMS_RANDOM.VALUE(1,10000)); 
        QUAN := ROUND(DBMS_RANDOM.VALUE(100,200)); 
        BUY := ROUND(DBMS_RANDOM.VALUE(750,1000)); 
        W := ROUND(DBMS_RANDOM.VALUE(1,30));


    INSERT INTO SELLS              
     VALUES ( SALE_SEQ.NEXTVAL, 
              SELLERID,
              DA,
              PROID,
              QUAN,
              BUY,
              W        
              );  
    END LOOP;
END;  





-------INSERTING INTO ORDERS TABLE--------

DROP SEQUENCE ORDER_SEQ;

create SEQUENCE ORDER_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 ;

DECLARE 
DAT DATE;
CUSID ORDERS.CUS_ID%TYPE;
PAYID ORDERS.PAYMENT_ID%TYPE;
PROID ORDERS.PRODUCT_ID%TYPE;
QUAN ORDERS.QTY%TYPE;

BEGIN 
   DAT := '01-01-2016';
  FOR I IN 1..10000 LOOP
      
       
        CUSID := ROUND(DBMS_RANDOM.VALUE(1,10000));
        PAYID := CUSID;
        PROID := ROUND(DBMS_RANDOM.VALUE(1,10000)); 
        QUAN := ROUND(DBMS_RANDOM.VALUE(1,10)); 


    INSERT INTO ORDERS              
     VALUES ( ORDER_SEQ.NEXTVAL,
              CUSID,  
              DAT + DBMS_RANDOM.VALUE(1,365),
              PROID,
              QUAN,
              PAYID    
              );  
    END LOOP;
END;



-------INSERTING INTO STOCK TABLE--------


INSERT INTO STOCK (W_ID,PRODUCT_ID,QUANTITY) SELECT W_ID,PRODUCT_ID,QUANTITY FROM SELLS;


-------INSERTING INTO EMPDEPT TABLE--------

INSERT INTO EMPDEPT(DEPT_ID,DEPT_NAME) VALUES (1,'WAREHOUSE');
INSERT INTO EMPDEPT(DEPT_ID,DEPT_NAME) VALUES (2,'HEADQUATERS');
INSERT INTO EMPDEPT(DEPT_ID,DEPT_NAME) VALUES (3,'DATA ANALYSIS');
INSERT INTO EMPDEPT(DEPT_ID,DEPT_NAME) VALUES (4,'MARKETING');




-------INSERTING INTO EMPLOYEE TABLE--------

DROP SEQUENCE EMP_SEQ;

create SEQUENCE EMP_SEQ START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999 ;

DECLARE 
NAM EMPLOYEE.NAME%TYPE;
AGE EMPLOYEE.AGE%TYPE;
DEP EMPLOYEE.DEPT_ID%TYPE;
SAL EMPLOYEE.SALARY%TYPE;
SALA EMPLOYEE.SALARY%TYPE;

BEGIN 

  FOR I IN 1..200 LOOP
  
        NAM := DBMS_RANDOM.STRING('U',10);
        AGE := ROUND(DBMS_RANDOM.VALUE(25,60));
        SAL := ROUND(DBMS_RANDOM.VALUE(3,10)); 
        DEP := ROUND(DBMS_RANDOM.VALUE(1,4)); 

        SALA := 10000*SAL;

    INSERT INTO EMPLOYEE              
     VALUES ( EMP_SEQ.NEXTVAL,
              NAM ,
              AGE,
              1234567890+I,
              SALA,
              DEP    
              );  
    END LOOP;
END; 



-------INSERTING INTO WAREHOUSE_EMP TABLE--------

INSERT INTO WAREHOUSE_EMP ( W_ID, EMP_ID ) SELECT ROUND(DBMS_RANDOM.VALUE(1,30)), EMP_ID FROM EMPLOYEE WHERE DEPT_ID=1; 